spring:
  config:
    import: application-private.yml
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password:


  #  h2:
#    console:
#      enabled: true
#
  jpa:
    show-sql: true
    properties:
      hibernate:
      format_sql: true
    hibernate:
      ddl-auto: update
  logging:
    level:
      org:
        hibernate: trace






---
spring:
  profiles:
    active: local

swagger:
  host: localhost:8080
  protocol: http

---

spring:
  config:
    activate:
      on-profile: dev


swagger:
  host: api.surbey.kro.kr
  protocol: https

---

spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/surbey?rewriteBatchedStatements=true&profileSQL=true&&serverTimezone=Asia/Seoul&c=Slf4JLogger&maxQuerySizeToLog=200
    username: admin
    password: gist1234!
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true

